/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;

/**
 *
 * @author manue
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCocinero
     */
    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jLabelComida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jButtonVolverPrincipal = new javax.swing.JButton();
        jButtonEditarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenu.setText("MENÚ DEL DÍA");
        getContentPane().add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 50));

        jLabelComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/comida.png"))); // NOI18N
        getContentPane().add(jLabelComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 140));

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Desayuno", "Almuerzo", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMenu);
        if (jTableMenu.getColumnModel().getColumnCount() > 0) {
            jTableMenu.getColumnModel().getColumn(0).setResizable(false);
            jTableMenu.getColumnModel().getColumn(1).setResizable(false);
            jTableMenu.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 660, 170));

        jButtonVolverPrincipal.setText("MENU PRINCIPAL");
        jButtonVolverPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 140, -1));

        jButtonEditarMenu.setText("EDITAR MENU");
        getContentPane().add(jButtonEditarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 130, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 10, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverPrincipalActionPerformed
        this.dispose();
        new JFramePrincipal().setVisible(true);
    }//GEN-LAST:event_jButtonVolverPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarMenu;
    private javax.swing.JButton jButtonVolverPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMenu;
    // End of variables declaration//GEN-END:variables

    public void setjButtonEditarMenuVisible() {
        jButtonEditarMenu.setVisible(false);
    }
}
